# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Colten/Dropbox/_SCHOOL/ECE_540_SoC_Design/Final_Project/Labyrinth/accel/icon_rom_1/icon_rom.xci
# IP: The module: 'icon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Colten/Dropbox/_SCHOOL/ECE_540_SoC_Design/Final_Project/Labyrinth/accel/icon_rom_1/icon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icon_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Colten/Dropbox/_SCHOOL/ECE_540_SoC_Design/Final_Project/Labyrinth/accel/icon_rom_1/icon_rom.xci
# IP: The module: 'icon_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Colten/Dropbox/_SCHOOL/ECE_540_SoC_Design/Final_Project/Labyrinth/accel/icon_rom_1/icon_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icon_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
